<?php
include_once ("view/header.html");
include_once ("view/nav.html");
?>
<main id="index">
    <section id="news" class="box">
        <img src="bilder/logo/LogoKonzeptSternBackgroundTransparent.png" alt="" id="indexBild">
        <section id="welcomeText1" class="longtext"> Willkommen bei <b>StarWatch</b>, der sozialen Streaming-Plattform. Hier kannst du deine Lieblingsfilme und -Serien online mit Freunden ansehen.
            Logge dich einfach ein, verlinke deine Netflix-, Maxdome- und Amazon-Prime-Accounts, und plane Events für Filme und Serien deiner Wahl mit anderen Mitgliedern aus aller Welt!
        </section>
        <section id="welcomeText2" class="longtext">
            Jeder kennt es: Man will sich auf einem gemeinsamen Abend treffen, um zusammen Filme zu schauen, aber findet
            keinen gemeinsamen Termin, Anreisen wären zu lang, und man hat nicht genug Platz in der Wohnung.
            Mit StarWatch ist das alles kein Problem. Erstellt einfach ein Event mit euren Filmen und Serien,
            tagged eure Freunde, verbindet euch mit unserem Discord-Plugin, und los geht's!
            Ob Netflix, Maxdome oder Amazon Prime, hier gibt es alles, was das Herz begehrt. Und falls Ihr auf der Suche
            nach Leuten mit dem selben Geschmack teilt:
        </section>

    </section>
    <section id="sideview" class="box">
        <table id="eventcounter">
            <tr class="header"><th>Öffentliche Events</th><th></th><th><img src="bilder/calender2.png" alt="" id="calicon"></th></tr>
            <tbody>
            <tr><td class="date">03.02.2020</td><td class="time">17:30</td><td class="title">Black Mirror</td></tr>
            <tr><td class="date">05.02.2020</td><td class="time">20:30</td><td class="title">The Office</td></tr>
            <tr><td class="date">07.02.2020</td><td class="time">16:45</td><td class="title">2 Broke Girls</td></tr>
            <tr><td class="date">07.02.2020</td><td class="time">18:00</td><td class="title">Supergirl</td></tr>
            <tr><td class="date">08.02.2020</td><td class="time">12:15</td><td class="title">Parks and Recreation</td></tr>
            <tr><td class="date">08.02.2020</td><td class="time">15:30</td><td class="title">It's Always Sunny In Philadelphia</td></tr>
            <tr><td class="date">08.02.2020</td><td class="time">16:30</td><td class="title">Mayday</td></tr>
            <tr><td class="date">08.02.2020</td><td class="time">17:00</td><td class="title">Chicago Fire</td></tr>
            <tr><td class="date">09.02.2020</td><td class="time">20:00</td><td class="title">Family Guy</td></tr>
            <tr><td class="date">09.02.2020</td><td class="time">22:45</td><td class="title">American Horror Story</td></tr>
            </tbody>
        </table>
    </section>
</main>
<?php
include_once ("view/footer.html");