<?php
include_once ("view/header.html");
include_once ("view/nav.html");
?>
<main id="index">
    <section id="news" class="box">
        <span> Willkommen bei StarWatch, der sozialen Streaming-Plattform. Hier kannst du deine Lieblingsfilme und -Serien online mit Freunden ansehen.
        Logge dich einfach ein, verlinke deine Netflix-, Maxdome- und Amazon-Prime-Accounts, und plane Events für Filme und Serien deiner Wahl mit anderen Mitgliedern aus aller Welt!</span>

    </section>
    <section id="sideview" class="box">
        <table id="eventcounter">
            <tr class="header"><th>Events</th></tr>
            <tbody>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            <tr><td class="date">19.03.2020</td><td class="time">05:30</td><td class="title">Collen</td></tr>
            </tbody>
        </table>
    </section>
</main>
<?php
include_once ("view/footer.html");