<?php
include_once ("view/header.html");
include_once ("view/navLoggedin.html");
?>
<main id="preview">
    <section id="previewText">
        <section id="Text" class="box">
            <p class="longtext">
                In der zauberhaften Verfilmung von J. K. Rowlings Weltbestseller erfährt Harry Potter an seinem 11. Geburtstag, dass seine verstorbenen Eltern mächtige Zauberer waren und auch er selbst magische Kräfte besitzt.
                Als er von Hogwarts, der Schule für Hexerei und Zauberei, aufgenommen wird, erlebt Harry das Abenteuer seines Lebens.
                Er lernt Quidditch, das hoch in der Luft gespielt wird, und auf dem Weg, sich einem schwarzen Magier zu stellen, der ihn vernichten will, muss Harry eine spannende Schachpartie mit lebenden Figuren überstehen.
                Treffen wir uns auf Gleis 9 3/4 zum Start eines außergewöhnlichen Abenteuers!
            </p>
        </section>
        <button><b>+</b> Zu Event hinzufügen</button>
    </section>
    <section id="previewImage">
        <section id="filmLogoSec">
            <img src="bilder/filme/hp1logo.png" alt="Harry Potter und der Stein der Weisen" id="filmLogo" />
        </section>
        <img src="bilder/filme/hp1.jpg" alt="Harry Potter und der Stein der Weisen" />
        <section id="companylogos">
            <img src="bilder/companylogos/netflix.png" alt="Netflix" class="companylogo" title="Netflix"/>
            <img src="bilder/companylogos/amazon.png" alt="Amazon Prime" class="companylogo" title="Amazon Prime"/>
        </section>
    </section>
</main>
<?php
include_once ("view/footer.html");
