<?php
include_once ("view/header.html");
include_once ("view/navLoggedin.html");
?>

<main id="series">
    <section id="diashow">
        <section class="purpleline"></section>
        <section id="imagelist">
            <img/>
            <img/>
            <img/>
            <img src="">
            <img src="">
        </section>
        <section class="purpleline"></section>
    </section>
</main>

<?php
include_once ("view/footer.html");
